name: 'hot-diggity-dag'
version: 'hotdog 1.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project. 
# In dbt Cloud IDE, this field is unused.
profile: 'joey-chestnut'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

seeds:
  node_color: "#e1ad01" # mustard yellow

models:
  node_color: "#995f4c" # butter dog brown
      
snapshots:
  node_color: "#cc2522" # ketchup red
  
sources:
  node_color: "#ede5d2" # hotdog bun gold
  
tests:
  node_color: "#a57f01" # relish green
  
analysis:
  node_color: "#b5d668" # spicy sport pepper green

metrics:
  node_color: "#ede5d2" # chili dog red brown
  
exposures:
  node_color: "#ede5d2" # onion white
  
  
    
